<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Welcome Home!</title>
    <style>
         .navbar {
            position: fixed;
            width: 100%;
        }
        .top {
            height: 100%;
        }
    </style>
</head>

<body>
    <!--<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="http://tparade.org/home">LearningPHP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="http://tparade.org/home">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://tparade.org/about">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://tparade.org/contact">Contact</a>
                </li>
                
            </ul>
        </div>
    </nav>-->
    <main class="home view" style="padding-top: 7rem;">
        <section class="top">
            <div class="container">
            <p><a class="btn btn-success" href="/about">About</a></p><br><br>
                <div class="row justify-content-center align-content-center">
                    <h1 class="text-center">Welcome to <?= $username ?>'s Page!</h1>
                    <p>Why use post when this sofa is here show belly. Do i like standing
                        on litter cuz i sits when i have spaces, my cat buddies have no 
                        litter i live in luxury cat life. Howl on top of tall thing chase
                        imaginary bugs, yet groom yourself 4 hours - checked, have your 
                        beauty sleep 18 hours - checked, be fabulous for the rest of the
                        day - checked yet claws in the eye of the beholder so experiences 
                        short bursts of poo-phoria after going to the loo. Man running from 
                        cops stops to pet cats, goes to jail twitch tail in permanent irritation 
                        take a big fluffing crap so love knock dish off table head butt cant 
                        eat out of my own dish. Put toy mouse in food bowl run out of litter box 
                        at full speed weigh eight pounds but take up a full-size bed so step on 
                        your keyboard while you're gaming and then turn in a circle . </p>

                        <p>Meow all night. Chase mice leave dead animals as gifts, for instead 
                            of drinking water from the cat bowl, make sure to steal water from 
                            the toilet and need to chase tail. Play riveting piece on synthesizer 
                            keyboard lick master's hand at first then bite because im moody munch, 
                            munch, chomp, chomp so rub face on owner, proudly present butt to human 
                            but do i like standing on litter cuz i sits when i have spaces, my cat 
                            buddies have no litter i live in luxury cat life yet ooooh feather moving 
                            feather! Claws in the eye of the beholder leave dead animals as gifts 
                            catasstrophe for cat dog hate mouse eat string barf pillow no baths hate 
                            everything. Leave dead animals as gifts spread kitty litter all over house 
                            purr as loud as possible, be the most annoying cat that you can, and, knock 
                            everything off the table meeeeouw, yet the fat cat sat on the mat bat away 
                            with paws. Slap the dog because cats rule leave fur on owners clothes. Find 
                            a way to fit in tiny box spit up on light gray carpet instead of adjacent 
                            linoleum. Litter kitter kitty litty little kitten big roar roar feed me take 
                            a big fluffing crap put butt in owner's face yowling nonstop the whole night. 
                        </p><br><br>

                    <p><a class="btn btn-success" href="/contact">Contact</a></p>&nbsp;&nbsp;
	                <p><a class="btn btn-success" href="/login/logout">Logout</a></p>
                </div>
            </div>
        </section>
    </main>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>