<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Submitted</title>
    <style>
         .navbar {
            position: fixed;
            width: 100%;
        }
        .top {
            height: 100%;
        }
    </style>
</head>
<body>
<!--<nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="http://tparade.org/home">LearningPHP</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="http://tparade.org/home">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://tparade.org/about">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://tparade.org/contact">Contact</a>
                </li>
             
                </ul>
            </div>
        </nav>-->
    <main class="submit view" style="padding-top: 7rem;">
        <section class="top">
            <div class="container">
                <div class="row flex-column justify-content-center align-content-center">
                <h1 class="text-center">Thank you, <?= $fname ?>!</h1>
                <p>Dear <?= $fname ?>,</p>
                <p>A confirmation e-mail was sent to your e-mail address: <?= $email ?></p>
                <p>Review your message and order below for further confirmation:</p>
                <p><?= $message ?></p>

	            <p><a href="/home" class="btn btn-success">< Back Home</a></p>
                </div>
            </div>
        </section>
    </main>
    
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>